#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
GH_REPO="${GH_REPO:-}" # owner/repo for gh writes; empty = infer from cwd
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# _gh_ready — gh installed and authenticated?
_gh_ready() { command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; }

# preflight_gh — prove gh can actually reach the repo BEFORE any stage asks for
# a credential. A token that cannot resolve the repo must fail here, not after
# the human has minted a password. Call once, right after banner.
preflight_gh() {
  local out="" rc=0
  if ! command -v gh >/dev/null 2>&1; then
    warn "gh not installed — secrets will be skipped"; return 1
  fi
  if ! gh auth status >/dev/null 2>&1; then
    warn "gh not authenticated — run: gh auth login"; return 1
  fi
  if [[ -n "$GH_REPO" ]]; then
    out=$(gh repo view "$GH_REPO" --json nameWithOwner 2>&1 >/dev/null) || rc=$?
  else
    out=$(gh repo view --json nameWithOwner 2>&1 >/dev/null) || rc=$?
  fi
  (( rc == 0 )) && return 0
  warn "gh cannot reach ${GH_REPO:-the current repo}: ${out%%$'\n'*}"
  note "fix the token scope now, or every secret below will be skipped"
  return 1
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh, targeting
# $GH_REPO when set. Reports gh's own error rather than hiding it: a silent
# "skipped" reads as done and is how a wizard finishes with nothing written.
set_secret() {
  local name="$1" value="$2" err="" rc=0
  if ! _gh_ready; then
    err="gh not installed or not authenticated"; rc=1
  elif [[ -n "$GH_REPO" ]]; then
    err=$(printf '%s' "$value" | gh secret set "$name" --repo "$GH_REPO" 2>&1 >/dev/null) || rc=$?
  else
    err=$(printf '%s' "$value" | gh secret set "$name" 2>&1 >/dev/null) || rc=$?
  fi
  if (( rc == 0 )); then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
    return 0
  fi
  err="${err%%$'\n'*}"; [[ -n "$err" ]] || err="gh exited $rc"
  SKIPPED+=("GitHub secret $name — $err")
  warn "skipped GitHub secret $name: $err"
  return 0
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2" err="" rc=0
  if ! _gh_ready; then
    err="gh not installed or not authenticated"; rc=1
  elif [[ -n "$GH_REPO" ]]; then
    err=$(gh variable set "$name" --repo "$GH_REPO" --body "$value" 2>&1 >/dev/null) || rc=$?
  else
    err=$(gh variable set "$name" --body "$value" 2>&1 >/dev/null) || rc=$?
  fi
  if (( rc == 0 )); then
    printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
    return 0
  fi
  err="${err%%$'\n'*}"; [[ -n "$err" ]] || err="gh exited $rc"
  SKIPPED+=("GitHub variable $name — $err")
  warn "skipped GitHub variable $name: $err"
  return 0
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# Cloud Scheduler → workflow_dispatch for clock.yml. See docs/SCHEDULER.md.
# Idempotent: re-running updates the four jobs in place. The PAT goes from
# the clipboard into the job headers and nowhere else.
TOTAL_STAGES=2
TOTAL_MINUTES=6
PROJECT="${GCP_PROJECT:-bcns-leads}"
LOCATION="${GCP_LOCATION:-us-central1}"
REF="${CLOCK_REF:-main}"
URI="https://api.github.com/repos/bcn-services/bcns-internal/actions/workflows/clock.yml/dispatches"

banner "Cloud Scheduler for clock.yml"

stage "GCP — enable Cloud Scheduler" 2
say "Checks gcloud auth (a re-auth prompt may appear) and enables the API in $PROJECT."
gcloud auth print-access-token >/dev/null 2>&1 || gcloud auth login --update-adc
gcloud services enable cloudscheduler.googleapis.com --project "$PROJECT"
say "API enabled."

stage "GitHub — fine-grained PAT for dispatch" 4
say "The PAT is the only credential the scheduler holds."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Resource owner: bcn-services. Repository access: only bcns-internal."
step "Repository permissions: Actions → Read and write. Nothing else. Generate."
ask_secret PAT "Paste the PAT:"
[[ -n "$PAT" ]] || { warn "no PAT, stopping"; exit 1; }
job() { # name cron
  local name="$1" cron="$2" verb=create
  gcloud scheduler jobs describe "$name" --project "$PROJECT" --location "$LOCATION" >/dev/null 2>&1 && verb=update
  gcloud scheduler jobs "$verb" http "$name" \
    --project "$PROJECT" --location "$LOCATION" \
    --schedule "$cron" --time-zone UTC \
    --uri "$URI" --http-method POST \
    --headers "Authorization=Bearer $PAT,Accept=application/vnd.github+json,User-Agent=bcns-clock" \
    --message-body "{\"ref\":\"$REF\",\"inputs\":{\"schedule\":\"$cron\"}}" \
    --attempt-deadline 60s --max-retry-attempts 3 --format=none
  printf '  %s✓ %s%s %s (%s)\n' "$GREEN" "$verb" "$RESET" "$name" "$cron"
}
job clock-poll        '*/20 8-20 * * 1-5'
job clock-touch       '0 14 * * 1-5'
job clock-source      '0 13 * * 1'
job clock-personalize '30 13 * * 1-5'
unset PAT
note "ref=$REF — the jobs dispatch clock.yml on that branch."

finish
